baseURL: https://rishabhsinhablog.netlify.app/
languageCode: en-us
title: Rishabh Sinha
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Explore
    subtitle: |-
      Personal Website
    title: Hi, my name is Rishabh
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Marylebone
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: rishabh.sinha357@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (+44) 7414114090
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
#      - icon: fa-twitter
#        label: Twitter
#        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/rishabh.sinha.3720
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/rishabhsinha98/
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/PhugoidMode
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/rishabh--sinha/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: Sinha
    title: Rishabh
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Creative Writing Exercises  # Top left 
        title: Writing
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: Istanbul AirBnB Price Analysis  # Top right
        title: A Regression Analysis on the Price of AirBnBs in Istanbul
        url: blogs/Group_10_Assignment.html
      - image: JetXXPEC.jpg
        subtitle: An independently designed and built jet engine  # Middle left
        title: JetX Engineering
        url: blogs/jetx
      - image: pic04.jpg
        subtitle: Working with schools and local communities to promote STEM learning
        title: Science Outreach
        url: blogs/blogfour
      - image: film.jpg
        subtitle: Analysis of Movie Ratings
        title: Coursework Example
        url: blogs/Website_Homework.html
      - image: pic06.jpg
        subtitle: Interview in the Telegraph Newspaper
        title: Feature in The Telegraph
        url: blogs/blogsix
  two:
    buttonText: Explore  # Need \n at the end of every sentence
    enable: yes
    subtitle: "Rishabh was born in the east Indian city of Calcutta, and grew 
    up in Newcastle upon Tyne, northern England, attending the Newcastle Royal 
    Grammar School. He received the Arkwright Engineering Scholarship, and a Gold 
    CREST award for a six month project with Nissan.\n Going on to study Aerospace
    Systems Engineering at the University of Glasgow, he joined
    several engineering-focused societies, such as JetX Engineering, worked as 
    a research assistant in the Fluid-Structures Interaction group, and was a
    TA for mathematics. \n During this time, he interned in an engineering 
    consultancy (Transmission Dynamics), served as a Young Professional 
    Ambassador for the Institution of Engineering and Technology, and interned
    at Barclays Investment Bank. \n He is now studying for a Master's in 
    Financial Analysis at London Business School. \n \n In his spare time, he 
    enjoys reading, cooking, AC/DC, and Pink Floyd. \n"
    title: About Rishabh
    url: blogs
